config/routes.rb
Rails.application.routes.draw do
  get 'players/index'

  get 'team/index'

  get 'account/dashboard'

  namespace :account do
    resources :dashboard, :teams
    put 'teams/:id/set_draft', to: 'teams#set_draft', as: 'set_draft'
    put 'teams/:id/set_ready', to: 'teams#set_ready', as: 'set_ready'
    put 'teams/:id/set_captain', to: 'teams#set_captain', as: 'set_captain'
    post '/teams/:id/add_player', to: 'teams#add_player', as: 'add_team_player'
    delete '/teams/:id/remove_player', to: 'teams#remove_player', as: 'remove_player'
  end

  get 'management', to: 'management#index'
  get 'parse_results', to: 'management#parse_results', as: 'parse_results'
  get 'process_results', to: 'management#process_results', as: 'process_results'
  get 'make_ready_teams_active', to: 'management#make_ready_teams_active', as: 'make_ready_teams_active'
  get 'make_active_teams_draft', to: 'management#make_active_teams_draft', as: 'make_active_teams_draft'

  resources :user_teams, path: '/account/teams'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Upmin::Engine => '/admin'
  root to: 'static_page#homepage'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :teams
  resources :players

  get '/players/:id/detail_team_manage', to: 'players#detail_team_manage', as: 'player_detail_team_manage'

  resources :user_player_deals
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :league
  belongs_to :venue
  belongs_to :parser
  has_many :team_participations
  has_many :team, :through => :team_participations

  enum status: [
    :upcoming,
    :finished,
    :parsed,
    :processed,
    :archived
  ]

  enum parser: [
    :hokejbal_cz,
    :onlajny_com
  ]

  scope :in_round, -> {
    where("term between ? and ?",
          ApplicationController.helpers.prev_update,
          ApplicationController.helpers.next_update)
  }
end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :teams
  has_many :user_teams
  belongs_to :sport
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user

  enum event: [
    :user_team_create,
    :user_team_player_assign,
    :user_score_update_player
  ]

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  belongs_to :player_role
  has_many :user_player_deals
  has_many :user_teams, :through => :user_player_deals
end

app/models/player_role.rb
class PlayerRole < ActiveRecord::Base
  has_many :players
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :leagues
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
  belongs_to :league
  has_many :team_participations
  has_many :games, :through => :team_participations
end

app/models/team_participation.rb
class TeamParticipation < ActiveRecord::Base
  belongs_to :team
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :player, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :user_teams, :dependent => :destroy

  def set_default_role
    self.role ||= :user
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.skip_confirmation!
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauth_providers => [:facebook]
end

app/models/user_player_deal.rb
class UserPlayerDeal < ActiveRecord::Base
  belongs_to :player
  belongs_to :user_team
end

app/models/user_team.rb
class UserTeam < ActiveRecord::Base
  belongs_to :user
  belongs_to :league
  has_many :user_player_deals, :dependent => :destroy
  has_many :players, :through => :user_player_deals

  enum status: %i[draft ready active finished archived]

  scope :draft, -> { where(status: statuses[:draft]) }
  scope :ready, -> { where(status: statuses[:ready]) }
  scope :active, -> { where(status: statuses[:active]) }
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :games
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only

  def index
    @games_in_round = Game.in_round
  end

  def set_ready_teams_active
    update = UserTeam.ready.update_all(status: UserTeam.statuses[:active])
    redirect_to management_path(), notice: "Teams actived: #{update.to_i}"
  end

  def set_active_teams_draft
    update = UserTeam.active.update_all(status: UserTeam.statuses[:draft])
    redirect_to management_path(), notice: "Teams drafted: #{update.to_i}"
  end

  def parse_results
    game_for_parse = Game.first
    Parser.parse(game_for_parse)
  end

  def process_results
    raise 'run rake results:process'
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper

  def next_update
    today = Date.today
    (today + (Settings.update_day - today.cwday) % 7).midnight # saturday
  end

  def prev_update
    # next_update - 7.days
    next_update - 1.month
  end
end

app/helpers/logs_helper.rb
module LogsHelper
  def create_log (user, event, key, value)
    Log.create(user_id: user, event: event, event_key: key, event_value: value)
  end
end

app/helpers/management_helper.rb
module ManagementHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_teams_helper.rb
module UserTeamsHelper
  def user_add_check (player, team)
    sportName = team.league.sport.name
    sportNameCode = sportName.parameterize.underscore
    allow_players = Settings.sports[sportNameCode].rules.game.players.to_i
    check_result = { status: :success }

    # check count of players
    if user_team_players_count(team) >= allow_players
      check_result = { status: :error, notice: t('.too_much_players') }

    # check if already assigned
    elsif user_team_players(team).any? {|u| u.id == player.id}
      check_result = { status: :error, notice: t('.player_already_assigned') }

    # check count of players from same team
    elsif same_team_players_count(team, player) >= 3
      check_result = { status: :error, notice: t('.too_much_players_from_same_team') }
    end

    return check_result
  end

  def same_team_players_count (team, player)
    user_team_players(team).select{|p| p.team.id == player.team.id}.count.to_i
  end

  def user_team_players (team)
    team.players
  end

  def user_team_players_count (team)
    user_team_players(team).count.to_i
  end
end

app/views/management/_sidebar.html.slim
aside.sidebar
  ul
    li
      a href=""
        .fa.fa-wrench
        | Správa
    li
      a href=""
        .fa.fa-gear
        | Nastavení

app/views/management/index.html.slim
= render 'shared/header'

= render 'shared/menu'

br

.row
  .col-sm-3
    = render 'management/sidebar'
  .col-sm-9
    .row.container-fluid
      .col-xs-12
        h1 Management

        .panel.panel-default
          .panel-heading
            h3.panel-title
              .fa.fa-database
              | Status
          .panel-body
            .row
              .col-sm-4
                | Rozpracované týmy:
                span.label.label-default =< UserTeam.draft.count
              .col-sm-4
                | Připravené týmy:
                span.label.label-info =< UserTeam.ready.count
              .col-sm-4
                | Aktivní týmy ve hře:
                span.label.label-success =< UserTeam.active.count
            br
            .row
              .col-sm-6
                | Začátek kola:
                b =< l prev_update, format: :long
              .col-sm-6
                | Obnova kola:
                b =< l next_update, format: :long

        .panel.panel-default
          .panel-heading
            h3.panel-title
              .fa.fa-gear
              | Správa kol
          .panel-body
            .text-center
              .btn-group
                = link_to 'Obnovit týmy', management_path(), class: 'btn btn-primary'
            .text-center nebo
            .text-center
              .btn-group
                = link_to 'Označit aktivní týmy jako dohrané', management_path(), class: 'btn btn-sm btn-default'
                = link_to 'Označit aktivní týmy jako drafty', make_active_teams_draft_path(), class: 'btn btn-sm btn-default'
                = link_to 'Zařadit připravené týmy do hry', make_ready_teams_active_path(), class: 'btn btn-sm btn-default'

        .panel.panel-default
          .panel-heading
            h3.panel-title
              .fa.fa-gear
              | Zpracování výsledků
          .panel-body
            .row
              .col-sm-6.text-center
                h4 Parsování výsledků
                = link_to 'Stáhnout výsledky', parse_results_path(), class: 'btn btn btn-primary'
              .col-sm-6.text-center
                h4 Počítání výsledků
                = link_to 'Parsovat stáhnuté', process_results_path(), class: 'btn btn btn-primary'

        .panel.panel-default
          .panel-heading
            h3.panel-title
              .fa.fa-calendar
              | Hry v aktuálním kole
          .panel-body
            table.table
              thead
                tr
                  th
                  th id
                  th termín
                  th liga
                  th účastníci
                  th
              tbody
                - @games_in_round.each do |game|
                  tr
                    td
                      .fa.fa-play-circle-o
                      .fa.fa-circle-o-notch.fa-spin
                      .fa.fa-check
                    td
                      = game.id
                    td
                      = game.term
                    td
                      = game.league.name
                    td
                      = game.team.map{|t| t.name}.join(', ')
                    td
                      .btn-group.pull-right
                        = link_to 'parsovat', management_path(), class: 'btn btn-xs btn-info'
                        = link_to 'počítat', management_path(), class: 'btn btn-xs btn-warning'