config/routes.rb
Rails.application.routes.draw do
  get 'players/index'

  get 'team/index'

  get 'account/dashboard'

  namespace :account do
    resources :dashboard, :teams
    put 'teams/:id/set_draft', to: 'teams#set_draft', as: 'set_draft'
    put 'teams/:id/set_ready', to: 'teams#set_ready', as: 'set_ready'
    put 'teams/:id/set_captain', to: 'teams#set_captain', as: 'set_captain'
    post '/teams/:id/add_player', to: 'teams#add_player', as: 'add_team_player'
    delete '/teams/:id/remove_player', to: 'teams#remove_player', as: 'remove_player'
  end

  get 'management', to: 'management#index'
  get 'parse_results', to: 'management#parse_results', as: 'parse_results'
  get 'process_results', to: 'management#process_results', as: 'process_results'
  get 'make_ready_teams_active', to: 'management#make_ready_teams_active', as: 'make_ready_teams_active'
  get 'make_active_teams_draft', to: 'management#make_active_teams_draft', as: 'make_active_teams_draft'

  resources :user_teams, path: '/account/teams'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Upmin::Engine => '/admin'
  root to: 'static_page#homepage'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :teams
  resources :players

  get '/players/:id/detail_team_manage', to: 'players#detail_team_manage', as: 'player_detail_team_manage'

  resources :user_player_deals
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :league
  belongs_to :venue
  belongs_to :parser
  has_many :team_participations
  has_many :team, :through => :team_participations

  enum status: [
    :upcoming,
    :finished,
    :parsed,
    :processed,
    :archived
  ]

  enum parser: [
    :hokejbal_cz,
    :onlajny_com
  ]

  scope :in_round, -> {
    where("term between ? and ?",
          ApplicationController.helpers.prev_update,
          ApplicationController.helpers.next_update)
  }
end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :teams
  has_many :user_teams
  belongs_to :sport
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user

  enum event: [
    :user_team_create,
    :user_team_player_assign,
    :user_score_update_player
  ]

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  belongs_to :player_role
  has_many :user_player_deals
  has_many :user_teams, :through => :user_player_deals
end

app/models/player_role.rb
class PlayerRole < ActiveRecord::Base
  has_many :players
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :leagues
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
  belongs_to :league
  has_many :team_participations
  has_many :games, :through => :team_participations
end

app/models/team_participation.rb
class TeamParticipation < ActiveRecord::Base
  belongs_to :team
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :player, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :user_teams, :dependent => :destroy

  def set_default_role
    self.role ||= :user
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.skip_confirmation!
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauth_providers => [:facebook]
end

app/models/user_player_deal.rb
class UserPlayerDeal < ActiveRecord::Base
  belongs_to :player
  belongs_to :user_team
end

app/models/user_team.rb
class UserTeam < ActiveRecord::Base
  belongs_to :user
  belongs_to :league
  has_many :user_player_deals, :dependent => :destroy
  has_many :players, :through => :user_player_deals

  enum status: %i[draft ready active finished archived]

  scope :draft, -> { where(status: statuses[:draft]) }
  scope :ready, -> { where(status: statuses[:ready]) }
  scope :active, -> { where(status: statuses[:active]) }
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :games
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper

  def next_update
    today = Date.today
    (today + (Settings.update_day - today.cwday) % 7).midnight # saturday
  end

  def prev_update
    # next_update - 7.days
    next_update - 1.month
  end
end

app/helpers/logs_helper.rb
module LogsHelper
  def create_log (user, event, key, value)
    Log.create(user_id: user, event: event, event_key: key, event_value: value)
  end
end

app/helpers/management_helper.rb
module ManagementHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_teams_helper.rb
module UserTeamsHelper
  def user_add_check (player, team)
    sportName = team.league.sport.name
    sportNameCode = sportName.parameterize.underscore
    allow_players = Settings.sports[sportNameCode].rules.game.players.to_i
    check_result = { status: :success }

    # check count of players
    if user_team_players_count(team) >= allow_players
      check_result = { status: :error, notice: t('.too_much_players') }

    # check if already assigned
    elsif user_team_players(team).any? {|u| u.id == player.id}
      check_result = { status: :error, notice: t('.player_already_assigned') }

    # check count of players from same team
    elsif same_team_players_count(team, player) >= 3
      check_result = { status: :error, notice: t('.too_much_players_from_same_team') }
    end

    return check_result
  end

  def same_team_players_count (team, player)
    user_team_players(team).select{|p| p.team.id == player.team.id}.count.to_i
  end

  def user_team_players (team)
    team.players
  end

  def user_team_players_count (team)
    user_team_players(team).count.to_i
  end
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      .container
        button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
        = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'SportFantasy.NET', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse.navbar-right
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  - if current_user.admin?
    li = link_to 'Manage', management_path
  li = link_to 'Profil', account_dashboard_path
  li = link_to 'Edit account', edit_user_registration_path
  li = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li = link_to 'Sign in', new_user_session_path
  li = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
  li = link_to 'Sign up', new_user_registration_path

- if user_signed_in?
  - if current_user.admin?
    li = link_to 'Admin', '/admin'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    meta[http-equiv="Content-Type" content="text/html; charset=utf-8"]
    title
      = content_for?(:title) ? yield(:title) : 'Sportfantasy'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Sportfantasy'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      .container
        .page
          = render 'layouts/messages'
          == yield

    footer
      .container
        .page
          .inner
            | SportFantasy &copy; 2015

app/views/shared/_header.html.slim
.row.container-fluid
  .col-xs-12
    = link_to root_path
      = image_tag 'sportfantasy.svg', class: 'logo'

app/views/shared/_menu.html.slim
nav.menu
  li = link_to 'Hokejbal', account_dashboard_path

nav.submenu
  li = link_to 'Ligy', teams_path
  li = link_to 'Týmy', teams_path
  li = link_to 'Hráči', players_path

app/views/shared/_score_bar.html.slim
.design-bar
  ul.score-bar
    / - @games.each do |game|
    li.score-item
      div
        .fa.fa-trophy KOV - HBT (1:3)
        | 18.4.2015 16.00
    li.score-item
      div
        .fa.fa-trophy HBC - KOV (2:1)
        | 18.4.2015 16.00
    li.score-item
      div
        .fa.fa-trophy ALP - HK (7:1)
        | 18.4.2015 16.00
    li.score-item
      div
        .fa.fa-trophy ELB - LET (4:5)
        | 16.4.2015 16.00
    li.score-item
      div
        .fa.fa-trophy KOV - HBT (1:3)
        | 18.4.2015 16.00
    li.score-item
      div
        .fa.fa-trophy HBC - KOV (2:1)
        | 18.4.2015 16.00
    li.score-item
      div
        .fa.fa-trophy ALP - HK (7:1)
        | 18.4.2015 16.00
    li.score-item
      div
        .fa.fa-trophy ELB - LET (4:5)
        | 16.4.2015 16.00

  ul.feature-bar
    / - @games.each do |game|
    li.feature-item
      div
        .fa.fa-calendar 18.4.2015 16.00
    li.feature-item
      div
        .fa.fa-calendar 18.4.2015 16.00
    li.feature-item
      div
        .fa.fa-calendar 18.4.2015 16.00
    li.feature-item
      div
        .fa.fa-calendar 16.4.2015 16.00
    li.feature-item
      div
        .fa.fa-calendar 18.4.2015 16.00
    li.feature-item
      div
        .fa.fa-calendar 18.4.2015 16.00

app/views/shared/_user_menu.html.slim
nav.usermenu
  li
    = link_to account_dashboard_path do
      .glyphicon.glyphicon-dashboard
      | Můj účet
  li
    = link_to account_teams_path do
      .glyphicon.glyphicon-link
      | Mé týmy
  / li
  /   = link_to account_dashboard_path do
  /     .glyphicon.glyphicon-stats
  /     | Body
  / li
  /   = link_to account_dashboard_path do
  /     .glyphicon.glyphicon-time
  /     | Historie
  / .player